### ISSUE TITLE
Case study: Content box seems smaller than PL

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/preview-website#179] opened 2018-07-03 16:03 UTC
See https://iatistandard.org/en/about/case-studies/raw-html-case-study-example/ vs http://iati.surge.sh/page-templates/01-2-1-case-study

**Comment by allthatilk** [comment] 2018-08-07 11:42
The example page no longer exists and was likely caused by the raw HTML template used. Closing issue.

**Closed by allthatilk** 2018-08-07 11:42 UTC
Labels: For pattern library
